name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
        - development
        - preview
        - production
        - production-apk

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v4

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: npm

    - name: 🏗 Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: 🔧 Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: 📦 Install dependencies
      run: npm ci

    - name: 🚀 Build app
      run: |
        # Determine build profile
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          PROFILE="${{ github.event.inputs.profile }}"
        elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
          PROFILE="production-apk"
        else
          PROFILE="preview"
        fi
        
        echo "Building with profile: $PROFILE"
        echo "PROFILE=$PROFILE" >> $GITHUB_ENV
        # Start build and wait for completion; capture JSON result
        eas build --platform android --profile "$PROFILE" --non-interactive --wait --json > build.json
        echo "EAS build finished. Captured output to build.json"
        # Parse build id from either array or object shape
        BUILD_ID=$(jq -r '.[0].id // .id // empty' build.json)
        echo "Build ID: ${BUILD_ID}"
        echo "build_id=${BUILD_ID}" >> $GITHUB_OUTPUT
      id: build

    - name: 📱 Download APK
      if: success()
      run: |
        # Resolve artifact URL and download APK
        ID=""
        if [ -f build.json ]; then
          ID=$(jq -r '.[0].id // .id // empty' build.json)
        fi
        if [ -z "$ID" ]; then
          echo "No build ID found in build.json; cannot download."
          exit 1
        fi
        
        echo "Fetching build details for $ID"
        # Add retry logic for build:view command
        for i in {1..3}; do
          echo "Attempt $i to fetch build details..."
          if eas build:view "$ID" --non-interactive --json > build_view.json 2>&1; then
            echo "Successfully fetched build details"
            break
          else
            echo "Failed to fetch build details (attempt $i)"
            if [ $i -eq 3 ]; then
              echo "All attempts failed. Build view output:"
              cat build_view.json || echo "No build_view.json file created"
              exit 1
            fi
            sleep 10
          fi
        done
        
        # Check if build_view.json has valid content
        if [ ! -s build_view.json ]; then
          echo "build_view.json is empty or doesn't exist"
          exit 1
        fi
        
        echo "Build view content:"
        cat build_view.json
        
        URL=$(jq -r '.artifacts.buildUrl // .artifacts.applicationArchiveUrl // .artifacts.appBuildUrl // empty' build_view.json)
        if [ -z "$URL" ] || [ "$URL" = "null" ]; then
          echo "Could not resolve artifact URL from build_view.json"
          echo "Available fields in artifacts:"
          jq -r '.artifacts // empty' build_view.json
          exit 1
        fi
        
        echo "Resolved artifact URL: $URL"
        
        # Determine file extension based on build type
        if [[ "$URL" == *".aab"* ]] || [[ "${{ env.PROFILE }}" == "production" ]]; then
          FILENAME="./app-build.aab"
        else
          FILENAME="./app-build.apk"
        fi
        
        echo "Downloading to: $FILENAME"
        curl -L "$URL" -o "$FILENAME"
        
        # Verify download
        if [ -f "$FILENAME" ]; then
          echo "Download successful. File size: $(du -h "$FILENAME" | cut -f1)"
          echo "ARTIFACT_FILE=$FILENAME" >> $GITHUB_ENV
        else
          echo "Download failed - file not found"
          exit 1
        fi

    - name: 📊 Build Summary
      if: success()
      run: |
        echo "## 🚀 Build Completed Successfully" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Profile:** ${PROFILE:-auto-detected}" >> $GITHUB_STEP_SUMMARY
        echo "**Platform:** Android" >> $GITHUB_STEP_SUMMARY
        echo "**Build ID:** ${{ steps.build.outputs.build_id }}" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Get artifact size
        if [ -f "$ARTIFACT_FILE" ]; then
          ARTIFACT_SIZE=$(du -h "$ARTIFACT_FILE" | cut -f1)
          ARTIFACT_TYPE=$(basename "$ARTIFACT_FILE" | cut -d'.' -f2 | tr '[:lower:]' '[:upper:]')
          echo "**${ARTIFACT_TYPE} Size:** $ARTIFACT_SIZE" >> $GITHUB_STEP_SUMMARY
        fi

    - name: 📦 Upload Android Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ env.PROFILE }}-${{ github.run_number }}
        path: ${{ env.ARTIFACT_FILE }}
        retention-days: 30

    - name: 💬 Comment PR
      if: github.event_name == 'pull_request' && success()
      uses: actions/github-script@v7
      env:
        BUILD_ID: ${{ steps.build.outputs.build_id }}
        PROFILE: ${{ env.PROFILE }}
      with:
        script: |
          const fs = require('fs');
          const artifactFile = process.env.ARTIFACT_FILE || './app-build.apk';
          const artifactExists = fs.existsSync(artifactFile);
          const artifactSize = artifactExists 
            ? require('child_process').execSync(`du -h "${artifactFile}"`).toString().split('\t')[0]
            : 'Unknown';
          const artifactType = artifactFile.includes('.aab') ? 'AAB' : 'APK';
          const lines = [
            '## 📱 Android Build Ready',
            '',
            '**Build completed successfully!**',
            `- **Profile:** ${process.env.PROFILE || 'auto-detected'}`,
            `- **${artifactType} Size:** ${artifactSize}`,
            '- **Download:** Check the "Artifacts" section in this workflow run',
            `- **Build ID:** ${process.env.BUILD_ID}`,
            '',
            `You can download and test the ${artifactType} from the workflow artifacts.`
          ];
          const bodyText = lines.join('\n');

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: bodyText
          });

  notify-failure:
    name: Notify Build Failure
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    
    steps:
    - name: 💬 Comment PR on Failure
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        COMMIT_SHA: ${{ github.sha }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      with:
        script: |
          const lines = [
            '## ❌ Android Build Failed',
            '',
            'The Android build failed for this PR. Please check the workflow logs for details.',
            '',
            '**Build Details:**',
            `- **Commit:** ${process.env.COMMIT_SHA}`,
            `- **Workflow:** [View logs](${process.env.RUN_URL})`,
            '',
            'Please fix the issues and push again to trigger a new build.'
          ];
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: lines.join('\n')
          });